# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI) in XFree86 4.1.0 and higher.

ccflags-y := -I$(srctree)/$(src)/cal_common

ccflags-$(CONFIG_SOC_ZUMA) += -I$(srctree)/$(src)/cal_9865
exynos-drm-$(CONFIG_SOC_ZUMA) += cal_9865/decon_reg.o
exynos-drm-$(CONFIG_SOC_ZUMA) += cal_9865/dsim_reg.o
exynos-drm-$(CONFIG_SOC_ZUMA) += cal_9865/dpp_reg.o
exynos-drm-$(CONFIG_SOC_ZUMA) += cal_9865/dqe_reg.o
exynos-drm-$(CONFIG_SOC_ZUMA) += cal_9865/hdr_reg.o

exynos-drm-y += exynos_drm_drv.o
exynos-drm-y += exynos_drm_crtc.o
exynos-drm-y += exynos_drm_connector.o
exynos-drm-y += exynos_drm_fb.o
exynos-drm-y += exynos_drm_format.o
exynos-drm-y += exynos_drm_gem.o
exynos-drm-y += exynos_drm_plane.o

exynos-drm-y += exynos_drm_debug.o
exynos-drm-y += exynos_drm_dqe.o
exynos-drm-y += exynos_drm_hibernation.o
exynos-drm-y += exynos_drm_partial.o
exynos-drm-y += exynos_drm_recovery.o

exynos-drm-$(CONFIG_DRM_SAMSUNG_DECON)		+= exynos_drm_decon.o
exynos-drm-$(CONFIG_DRM_SAMSUNG_DPP)		+= exynos_drm_dpp.o
exynos-drm-$(CONFIG_DRM_SAMSUNG_DSI)		+= exynos_drm_dsim.o
exynos-drm-$(CONFIG_DRM_SAMSUNG_TUI)		+= exynos_drm_tui.o
exynos-drm-$(CONFIG_DRM_SAMSUNG_WB)			+= exynos_drm_writeback.o

exynos-drm-$(CONFIG_EXYNOS_BTS)		+= exynos_drm_bts.o

obj-$(CONFIG_DRM_SAMSUNG)		+= exynos-drm.o
obj-y	+= panel/
